sudo: required
dist: trusty
addons:
  apt:
    packages:
    # - mysql-server-5.6
    # - mysql-client-core-5.6
    # - mysql-client-5.6
    - php5-mysql
    

services:
  - mysql

language: node_js
node_js: 6

os:
  - linux
  
before_install:
  - bash travis_mysql_5.7.sh
  - bash mysql-reset-root-password.sh
  - mysql --version
      
install:
  - npm install

script:
  # - npm run travix neko .
  - npm run travix node .
  # - npm run travix php .
  # - npm run travix java .
