sudo: required
dist: trusty

addons:
  apt:
    sources:
      - mysql-5.7-trusty
      - sourceline: 'ppa:ondrej/php'
    packages:
      - mysql-server

stages:
  - test
  # - deploy

language: node_js
node_js: 8

cache:
  directories:
    - $HOME/haxe

os:
  - linux
  # - osx

env:
  - HAXE_VERSION=3.4.7
  - HAXE_VERSION=latest
  
install:
  - npm i -g lix
  - lix install haxe $HAXE_VERSION
  - lix download
  - if [[ "$(haxe -version)" =~ ^4.* ]]; then sudo apt-get install php7.1-cli php7.1-mysql; else sudo apt-get install php5.6-cli php5.6-mysql; fi

  
script:
  - lix run travix node
  - lix run travix php

# jobs:
#   include:
#     # - stage: test # should uncomment this when there is no matrix above (e.g. only one os, one env, etc)
#     - stage: deploy
#       os: linux
#       install:
#         - npm i -g lix
#         - lix download
#       script: skip
#       env:
#         secure: xxxxxxxx
#       after_success:
#         - lix run travix install
#         - lix run travix release
